class ClothesData {
  String? cover;
  String? name;
  String? desc;
  String? value;
  int? rait;
  bool? isliked;
  int? reviews;
  ClothesData(
    this.cover,
    this.name,
    this.desc,
    this.value,
    this.rait,
    this.isliked,
    this.reviews,
  );
}

List<ClothesData> payments = [
  ClothesData(
    "img/first.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$212.99",
    5,
    false,
    7162,
  ),
  ClothesData(
    "img/hat1.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$50.99",
    5,
    false,
    1182,
  ),
  ClothesData(
    "img/w2.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$116.99",
    5,
    true,
    7162,
  ),
];

List<ClothesData> allData = [
  ClothesData(
    "img/first.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$212.99",
    5,
    false,
    7162,
  ),
  ClothesData(
    "img/w3.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$57.99",
    5,
    false,
    3562,
  ),
  ClothesData(
    "img/w4.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$20.99",
    5,
    false,
    6165,
  ),
  ClothesData(
    "img/hat1.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$50.99",
    5,
    false,
    1182,
  ),
  ClothesData(
    "img/hat2.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$116.99",
    5,
    true,
    8145,
  ),
  ClothesData(
    "img/w1.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$50.99",
    5,
    false,
    352,
  ),
  ClothesData(
    "img/w2.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$116.99",
    5,
    true,
    7162,
  ),
  ClothesData(
    "img/second.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$116.99",
    5,
    true,
    752,
  ),
  ClothesData(
    "img/third.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$250.99",
    5,
    false,
    1122,
  ),
  ClothesData(
    "img/fourth.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$200.99",
    5,
    false,
    862,
  ),
  ClothesData(
    "img/hat3.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$57.99",
    5,
    false,
    3462,
  ),
  ClothesData(
    "img/hat4.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$20.99",
    5,
    false,
    1132,
  ),
];
List<ClothesData> clothesData = [
  ClothesData(
    "img/first.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$212.99",
    5,
    false,
    7162,
  ),
  ClothesData(
    "img/second.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$116.99",
    5,
    true,
    752,
  ),
  ClothesData(
    "img/third.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$250.99",
    5,
    false,
    1122,
  ),
  ClothesData(
    "img/fourth.jpg",
    "Modern light clothes",
    "Dress modern",
    "\$200.99",
    5,
    false,
    862,
  ),
];

List<ClothesData> hatData = [
  ClothesData(
    "img/hat1.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$50.99",
    5,
    false,
    1182,
  ),
  ClothesData(
    "img/hat2.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$116.99",
    5,
    true,
    8145,
  ),
  ClothesData(
    "img/hat3.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$57.99",
    5,
    false,
    3462,
  ),
  ClothesData(
    "img/hat4.jpg",
    "Jordan Jumpman Washed Bucket Hat",
    "Hat modern",
    "\$20.99",
    5,
    false,
    1132,
  ),
];

List<ClothesData> watcheData = [
  ClothesData(
    "img/w1.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$50.99",
    5,
    false,
    352,
  ),
  ClothesData(
    "img/w2.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$116.99",
    5,
    true,
    7162,
  ),
  ClothesData(
    "img/w3.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$57.99",
    5,
    false,
    3562,
  ),
  ClothesData(
    "img/w4.jpg",
    "Black Citizen Analog Watch",
    "Watche modern",
    "\$20.99",
    5,
    false,
    6165,
  ),
];
